// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ProjectUsers     string
	Projects         string
	SchemaMigrations string
	TaskLabels       string
	TaskStates       string
	Tasks            string
	Users            string
	WorkLogs         string
}{
	ProjectUsers:     "project_users",
	Projects:         "projects",
	SchemaMigrations: "schema_migrations",
	TaskLabels:       "task_labels",
	TaskStates:       "task_states",
	Tasks:            "tasks",
	Users:            "users",
	WorkLogs:         "work_logs",
}
