// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Comments            string
	ProjectAssociations string
	Projects            string
	TaskStatuses        string
	Tasks               string
	Users               string
	WorkLogs            string
}{
	Comments:            "comments",
	ProjectAssociations: "project_associations",
	Projects:            "projects",
	TaskStatuses:        "task_statuses",
	Tasks:               "tasks",
	Users:               "users",
	WorkLogs:            "work_logs",
}
